# ~/.bashrc
#
# Si no está en modo interactivo, no hacer nada
[[ $- != *i* ]] && return

export DOTFILES="/home/aletheios/Documentos/Dotfiles"

#### Variables de Entorno ####
export SHELL_EXPORTS="$DOTFILES/shell/exports"
if [[ -f "$SHELL_EXPORTS" ]]; then
  source "$SHELL_EXPORTS"
fi

#### Alias ####
export SHELL_ALIASES="$DOTFILES/shell/aliases"
if [[ -f "$SHELL_ALIASES" ]]; then
  source "$SHELL_ALIASES"
fi

#### Cargar Funciones de Shell ####
export SHELL_FUNC_PATH="$DOTFILES/shell/functions"
if [[ -f "$SHELL_FUNC_PATH" ]]; then
  source "$SHELL_FUNC_PATH"
fi

#### Configuración de SSH ####
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
# Agregar clave SSH al agente
ssh-add -q ~/.ssh/id_ed25519 2>/dev/null


# Cargar bash-completion si existe
if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi


# enable zsh vi-mode
set -o vi

bind 'set bell-style none'
bind -x '"\C-p":clear'

PROMPT_COMMAND=set_prompt_bash
