" Olvidar vi
set nocompatible
" Para tener colores bonitos
 syntax enable
" Poder instalar plugins
filetype plugin on

" Puedes buscar archivos en los subdirectorios de tus subdirectorios(fzf - like)
set path+=**

" Enseña todos los patrones coincidentes para Tab Completion 
set wildmenu

" Para configurar busquedas semanticas (hay que tener ctags instalado)
command! Maketags !ctags -R .

" Para poder hacer como only y Tabonly
command! BufOnly execute '%bd | e# | bd#'

" para ver que tienes estas tecleando
set showcmd

