# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
alias ls='ls --color=auto'
alias grep='grep --color=auto'
#
# Prompt minimalista y atractivo
PS1='\[\e[0;36m\]\u\[\e[0m\] \[\e[0;32m\]\w\[\e[0m\] \[\e[0;35m\]>\[\e[0m\] '

# Clipboard management
alias clip='xclip -selection clipboard'

# Edit bashrc quickly
alias bashrc='nvim ~/.bashrc'

# Reload bashrc
alias reload='source ~/.bashrc'


# Second Brain configuration
export SB_PATH="$HOME/SecondBrain"
export SB_FUNC_PATH="$HOME/Dotfiles/bash/sb_functions"

# Load Second Brain functions
if [ -f "$SB_FUNC_PATH" ]; then
    source "$SB_FUNC_PATH"
  else
    echo "Warning: Second Brain functions file not found at $SB_FUNC_PATH"
fi

# General bash functions
export BASH_FUNC_PATH="$HOME/Dotfiles/bash/bash_functions"

# Load general functions
if [ -f "$BASH_FUNC_PATH" ]; then
    source "$BASH_FUNC_PATH"
fi
