# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Cargar bash-completion si existe
# if [ -f /usr/share/bash-completion/bash_completion ]; then
#     . /usr/share/bash-completion/bash_completion
# elif [ -f /etc/bash_completion ]; then
#     . /etc/bash_completion
# fi
# Prompt minimalista y atractivo
PS1='\[\e[0;36m\]\u\[\e[0m\] \[\e[0;32m\]\w\[\e[0m\] \[\e[0;35m\]>\[\e[0m\] '


bind -x '"\C-p":clear'

## ALIAS

alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Clipboard management
alias clip='xclip -selection clipboard'
# Edit bashrc quickly
alias bashrc='nvim ~/.bashrc'
# Reload bashrc
alias reload='source ~/.bashrc'


## Exports

## PATH

export DOTFILES="$HOME/Dotfiles/"
export CONFIG="$HOME/.config/"

export SECONDBRAIN="$HOME/SecondBrain"

export SB_FUNC_PATH="$DOTFILES/bash/sb_functions"

export GITHUB="https://github.com/Aletheios42"
export DOCKERHUB="https://hub.docker.com/repositories/alejandropintosdev"

# Load Second Brain functions
if [ -f "$SB_FUNC_PATH" ]; then
    source "$SB_FUNC_PATH"
  else
    echo "Warning: Second Brain functions file not found at $SB_FUNC_PATH"
fi

# General bash functions
export BASH_FUNC_PATH="$DOTFILES/bash/bash_functions"

# Load general functions
if [ -f "$BASH_FUNC_PATH" ]; then
    source "$BASH_FUNC_PATH"
fi


